version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    command:
      - bash
      - -c
      - |
          npm run start:dev
    volumes:
      - ./:/api/
